In [1]:
import numpy as np

In [2]:
np.__version__

'1.24.3'

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [4]:
# Why numpy
# -mathematical function
# Faster

In [5]:
l = [1, 2, 3, 4, 5]

In [6]:
arr = np.array(l)

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
type(np.array(1))

numpy.ndarray

In [9]:
arr.ndim

1

In [17]:
l = [1, 2, 3, 4, 5, 'Rishi']
arr1 = np.array(l)
arr1

array(['1', '2', '3', '4', '5', 'Rishi'], dtype='<U11')

In [18]:
arr.ndim

1

In [19]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

In [20]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr.ndim

1

In [23]:
l = [1, 2, 3, 4]

In [44]:
# matrix will be by default 2d

mat = np.matrix(l) 

In [45]:
mat

matrix([[1, 2, 3, 4]])

In [46]:
mat.ndim

2

In [47]:
np.matrix([[[1, 2], [5, 6], [7, 8]]])

ValueError: matrix must be 2-dimensional

In [48]:
np.array([[[1, 2], [5, 6], [7, 8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [49]:
# More way to convert to array

np.asarray([[[1, 2], [5, 6], [7, 8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [50]:
# Convert the input to an ndarray, but pass ndarray subclasses through

np.asanyarray([[[1, 2], [5, 6], [7, 8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [53]:
l = [1, 2, 3, 4]

In [54]:
mat = np.matrix(l) 

In [55]:
mat

matrix([[1, 2, 3, 4]])

In [56]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [57]:
t = ([1, 2, 3], [4, 5, 6])
type(t)

tuple

In [58]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
a = 5
np.array(a)

array(5)

In [61]:
l = [1, 2, 3, 4, 5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [66]:
arr[0]

1

In [67]:
arr[3]

4

In [78]:
# Shallow copy

a = arr 

In [79]:
a

array([1000,    2,    3,    4,    5])

In [80]:
arr[0] = 1000

In [81]:
arr

array([1000,    2,    3,    4,    5])

In [82]:
a

array([1000,    2,    3,    4,    5])

In [84]:
# Deep copy

b = a.copy() 

In [85]:
b

array([1000,    2,    3,    4,    5])

In [75]:
b[0] = 2000

In [76]:
b

array([2000,    2,    3,    4,    5])

In [77]:
a

array([1000,    2,    3,    4,    5])

In [86]:
#to create array >> .array, .asarray, .asanyarray, deep copy, shallow copy

In [87]:
# There are multiple ways to generating arrays

In [88]:
np.fromfunction(lambda i, j : i == j, shape = (3, 3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [92]:
arr

array([1000,    2,    3,    4,    5])

In [90]:
arr.shape

(5,)

In [89]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
arr1.shape

(2, 3)

In [93]:
arr.size

5

In [94]:
arr1.size

6

In [95]:
np.fromfunction(lambda i, j : i == j, shape = (3, 3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [96]:
np.fromfunction(lambda i, j : i * j, shape = (3, 3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [99]:
for i in range(5):
    print(i)

0
1
2
3
4


In [100]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [101]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [102]:
list(range(5))

[0, 1, 2, 3, 4]

In [118]:
iterable = (i*i for i in range(5))

In [119]:
np.fromiter(iterable, float) # by default it generates float

array([ 0.,  1.,  4.,  9., 16.])

In [120]:
iterable = (i*i for i in range(5))

In [121]:
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

In [107]:
np.fromstring('23 34 67', sep = ' ')

array([23., 34., 67.])

In [108]:
np.fromstring('23,34,67', sep = ',')

array([23., 34., 67.])

In [109]:
np.fromstring('Suhani,Ajay,Anwesha', sep = ',')

C:\Users\pulki\AppData\Local\Temp\ipykernel_2088\4232903791.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('Suhani,Ajay,Anwesha', sep = ',')


array([], dtype=float64)

In [122]:
arr.dtype

dtype('int32')

In [123]:
l = [1, 2, 3]
arr = np.array(l)
arr.dtype

dtype('int32')

In [124]:
l = [1, 2, 3, 'Rishi']
arr = np.array(l)
arr.dtype

# <U11 means string

dtype('<U11')

In [125]:
arr

array(['1', '2', '3', 'Rishi'], dtype='<U11')

In [126]:
list(range(5))

[0, 1, 2, 3, 4]

In [127]:
range(5)

range(0, 5)

In [129]:
list(range(1.0, 2.10)) # range cannot deal with float values

TypeError: 'float' object cannot be interpreted as an integer

In [130]:
np.arange(0.1, 10.2, 0.1)

array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,
        1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,
        2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,
        3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,
        4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,
        5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,
        6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,
        7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,
        8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9,
       10. , 10.1])

In [133]:
list(np.arange(0.1, 10.2, 0.1))

[0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6,
 0.7000000000000001,
 0.8,
 0.9,
 1.0,
 1.1,
 1.2000000000000002,
 1.3000000000000003,
 1.4000000000000001,
 1.5000000000000002,
 1.6,
 1.7000000000000002,
 1.8000000000000003,
 1.9000000000000001,
 2.0,
 2.1,
 2.2,
 2.3000000000000003,
 2.4000000000000004,
 2.5000000000000004,
 2.6,
 2.7,
 2.8000000000000003,
 2.9000000000000004,
 3.0000000000000004,
 3.1,
 3.2,
 3.3000000000000003,
 3.4000000000000004,
 3.5000000000000004,
 3.6,
 3.7,
 3.8000000000000003,
 3.9000000000000004,
 4.0,
 4.1,
 4.2,
 4.3,
 4.3999999999999995,
 4.5,
 4.6,
 4.7,
 4.8,
 4.9,
 5.0,
 5.1,
 5.2,
 5.3,
 5.4,
 5.5,
 5.6,
 5.7,
 5.8,
 5.9,
 6.0,
 6.1,
 6.2,
 6.3,
 6.4,
 6.5,
 6.6,
 6.7,
 6.8,
 6.9,
 7.0,
 7.1,
 7.2,
 7.3,
 7.4,
 7.5,
 7.6,
 7.7,
 7.8,
 7.9,
 8.0,
 8.1,
 8.2,
 8.3,
 8.4,
 8.5,
 8.6,
 8.7,
 8.8,
 8.9,
 9.0,
 9.1,
 9.2,
 9.3,
 9.4,
 9.5,
 9.6,
 9.700000000000001,
 9.8,
 9.9,
 10.0,
 10.1]

In [138]:
np.linspace(1, 5, 50)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [136]:
list(np.linspace(1, 5, 20)) #gives you linearly spaced values numbers are evenly spaced

[1.0,
 1.2105263157894737,
 1.4210526315789473,
 1.631578947368421,
 1.8421052631578947,
 2.052631578947368,
 2.263157894736842,
 2.473684210526316,
 2.6842105263157894,
 2.894736842105263,
 3.1052631578947367,
 3.3157894736842106,
 3.526315789473684,
 3.7368421052631575,
 3.9473684210526314,
 4.157894736842105,
 4.368421052631579,
 4.578947368421052,
 4.789473684210526,
 5.0]

In [143]:
np.logspace(1, 5, 20, base = 2) #gives you the logarithim spaced values

array([ 2.        ,  2.31422047,  2.6778082 ,  3.09851928,  3.58532838,
        4.14862018,  4.80041088,  5.55460457,  6.42728981,  7.43708284,
        8.60552469,  9.95754072, 11.5219723 , 13.3321921 , 15.42681597,
       17.85052668, 20.65502717, 23.90014339, 27.65510059, 32.        ])

In [145]:
np.logspace(1, 5, 20, base = 10)

array([1.00000000e+01, 1.62377674e+01, 2.63665090e+01, 4.28133240e+01,
       6.95192796e+01, 1.12883789e+02, 1.83298071e+02, 2.97635144e+02,
       4.83293024e+02, 7.84759970e+02, 1.27427499e+03, 2.06913808e+03,
       3.35981829e+03, 5.45559478e+03, 8.85866790e+03, 1.43844989e+04,
       2.33572147e+04, 3.79269019e+04, 6.15848211e+04, 1.00000000e+05])

In [147]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [150]:
np.zeros((3,4), int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [151]:
arr1 = np.zeros(5)
arr1.shape

(5,)

In [152]:
arr2 = np.zeros((3, 4))
arr2.shape

(3, 4)

In [153]:
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [154]:
arr2.ndim

2

In [155]:
arr3 = np.zeros((3, 3, 4))
arr3.shape

(3, 3, 4)

In [156]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [157]:
arr3.ndim

3

In [158]:
arr4 = np.zeros((2, 3, 4))
arr4.shape

(2, 3, 4)

In [159]:
arr4

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [163]:
arr4.ndim

3

In [161]:
arr5 = np.zeros((1, 3, 4))
arr5.shape

(1, 3, 4)

In [162]:
arr5

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [164]:
arr5.ndim

3

In [171]:
arr6 = np.zeros((2, 4, 3, 4))
arr6.shape

(2, 4, 3, 4)

In [172]:
arr6

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [173]:
arr6.ndim

4

In [169]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [175]:
arr = np.ones((3, 4))

In [176]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [178]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [179]:
arr * 3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [180]:
np.twos(5)

AttributeError: module 'numpy' has no attribute 'twos'