In [18]:
import numpy as np
arr = np.ones((3,4))

In [19]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
arr1 = np.zeros((2,4))

In [21]:
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [27]:
arr * 8

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [32]:
np.empty((3, 4), int)

array([[4128860, 6029375, 3801155, 5570652],
       [6619251, 7536754, 7340124, 7078005],
       [6881387, 4259932, 7340144, 6357060]])

In [33]:
np.empty((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
# n*n matrix # to calculate inverse of matrix
np.eye(5) 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [41]:
np.eye()

TypeError: eye() missing 1 required positional argument: 'N'

In [42]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [44]:
import pandas as pd
pd.DataFrame(arr)

,0,1,2,3
0,1.0,1.0,1.0,1.0
1,1.0,1.0,1.0,1.0
2,1.0,1.0,1.0,1.0


In [45]:
# extra topics
import random

In [60]:
random.choice((1, 2, 3, 4, 5))

4

In [61]:
random.choice(range(0, 20))

4

In [62]:
random.choice('Ajay')

'a'

In [66]:
random.randrange(1, 1000)

817

In [75]:
random.randrange(1, 1000)

851

In [76]:
random.random() # a random number is generated between 0 (included), 1 will be excluded

0.5386202292129758

In [82]:
lis = [1, 2, 3, 4, 5]
random.shuffle(lis)

In [83]:
lis

[5, 2, 3, 1, 4]

In [91]:
random.uniform(7, 14) #a number between 7 and 14

9.196932203542646

In [100]:
np.random.rand(2, 3)

array([[0.22738745, 0.11162921, 0.68323553],
       [0.57488276, 0.70968539, 0.48429198]])

In [101]:
np.random.rand(2)

array([0.74332098, 0.25415998])

In [102]:
np.random.randn(3 ,4)

array([[-0.06001265,  1.4904233 ,  1.29051084,  1.32419468],
       [ 1.61761734,  0.99669498, -0.67665245, -0.01490118],
       [-0.64278618, -0.43806379, -0.91052147,  1.80795249]])

In [103]:
np.random.random_sample()

0.07469900555716336

In [105]:
arr = np.random.randint(1, 5, size = (3, 4))

In [106]:
arr

array([[2, 4, 3, 2],
       [1, 1, 1, 4],
       [4, 2, 1, 3]])

In [107]:
arr.size

12

In [108]:
arr.shape

(3, 4)

In [109]:
arr.ndim

2

In [116]:
arr.reshape(2, 6) # array size cannot change, multiples of array size

array([[2, 4, 3, 2, 1, 1],
       [1, 4, 4, 2, 1, 3]])

In [117]:
arr.reshape(12)

array([2, 4, 3, 2, 1, 1, 1, 4, 4, 2, 1, 3])

In [118]:
arr.reshape(12, 1)

array([[2],
       [4],
       [3],
       [2],
       [1],
       [1],
       [1],
       [4],
       [4],
       [2],
       [1],
       [3]])

In [119]:
arr.reshape(1, 12)

array([[2, 4, 3, 2, 1, 1, 1, 4, 4, 2, 1, 3]])

In [121]:
arr.reshape(3, 4)

array([[2, 4, 3, 2],
       [1, 1, 1, 4],
       [4, 2, 1, 3]])

In [122]:
arr.reshape(4, -1)

array([[2, 4, 3],
       [2, 1, 1],
       [1, 4, 4],
       [2, 1, 3]])

In [123]:
arr.reshape(4, -1000)

array([[2, 4, 3],
       [2, 1, 1],
       [1, 4, 4],
       [2, 1, 3]])

In [125]:
arr.reshape(3, -1)

array([[2, 4, 3, 2],
       [1, 1, 1, 4],
       [4, 2, 1, 3]])

In [126]:
arr.reshape(-1, 4)

array([[2, 4, 3, 2],
       [1, 1, 1, 4],
       [4, 2, 1, 3]])

In [133]:
arr.reshape(-1000, 4)

array([[2, 4, 3, 2],
       [1, 1, 1, 4],
       [4, 2, 1, 3]])

In [134]:
arr.reshape(5, -1)

ValueError: cannot reshape array of size 12 into shape (5,newaxis)

In [135]:
arr.reshape(-1, 5)

ValueError: cannot reshape array of size 12 into shape (5)

In [140]:
arr

array([[2, 4, 3, 2],
       [1, 1, 1, 4],
       [4, 2, 1, 3]])

In [143]:
arr.reshape(4, 3).base

array([[2, 4, 3, 2],
       [1, 1, 1, 4],
       [4, 2, 1, 3]])

In [145]:
arr

array([[2, 4, 3, 2],
       [1, 1, 1, 4],
       [4, 2, 1, 3]])

In [146]:
arr.size

12

In [147]:
arr.reshape(2, 2, 3)

array([[[2, 4, 3],
        [2, 1, 1]],

       [[1, 4, 4],
        [2, 1, 3]]])

In [148]:
arr.reshape(4, 3, 1)

array([[[2],
        [4],
        [3]],

       [[2],
        [1],
        [1]],

       [[1],
        [4],
        [4]],

       [[2],
        [1],
        [3]]])

In [150]:
arr.reshape(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3)

array([[[[[[[[[[[[[[[[2, 4, 3],
                     [2, 1, 1]],

                    [[1, 4, 4],
                     [2, 1, 3]]]]]]]]]]]]]]]])

In [154]:
list = [1, 2, 3, 4]
arr = np.array(list)

In [155]:
arr

array([1, 2, 3, 4])

In [156]:
arr.ndim

1

In [158]:
arr2 = np.array([[2, 3], [4, 5]])
arr2

array([[2, 3],
       [4, 5]])

In [159]:
arr2.ndim

2

In [162]:
arr2 = np.zeros((3, 4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [161]:
arr2.ndim

2

In [173]:
arr3 = np.zeros((1, 3, 4)) # 3 rows, 4 columns >> 2d array + 1d
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [174]:
arr3.shape

(1, 3, 4)

In [175]:
arr3 = np.zeros((2, 3, 4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [176]:
arr3.shape

(2, 3, 4)

In [180]:
arr4 = np.zeros((1, 1, 3, 4))
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [182]:
arr4.shape

(1, 1, 3, 4)

In [183]:
arr4 = np.zeros((1, 2, 3, 4))
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [184]:
arr4.shape

(1, 2, 3, 4)

In [185]:
arr4 = np.zeros((2, 2, 3, 4))
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [187]:
arr4.shape

(2, 2, 3, 4)

In [188]:
arr4 = np.zeros((3, 4, 3, 4))
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [189]:
arr4 = np.ones((2, 2, 3, 4))
arr4

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [191]:
arr4.ndim

4

In [192]:
arr4.size

48

In [193]:
arr4.shape

(2, 2, 3, 4)

In [197]:
arr1 = np.random.randint(1, 10, (5, 6))
arr1

array([[2, 7, 2, 7, 5, 2],
       [1, 7, 1, 9, 9, 4],
       [2, 2, 1, 2, 7, 6],
       [8, 4, 8, 1, 1, 1],
       [4, 6, 7, 2, 3, 6]])

In [198]:
arr1 > 5

array([[False,  True, False,  True, False, False],
       [False,  True, False,  True,  True, False],
       [False, False, False, False,  True,  True],
       [ True, False,  True, False, False, False],
       [False,  True,  True, False, False,  True]])

In [200]:
arr1[arr1 > 5] # give me all the values in array where condition is true

array([7, 7, 7, 9, 9, 7, 6, 8, 8, 6, 7, 6])

In [201]:
arr1[arr1 < 5]

array([2, 2, 2, 1, 1, 4, 2, 2, 1, 2, 4, 1, 1, 1, 4, 2, 3])

In [202]:
arr1

array([[2, 7, 2, 7, 5, 2],
       [1, 7, 1, 9, 9, 4],
       [2, 2, 1, 2, 7, 6],
       [8, 4, 8, 1, 1, 1],
       [4, 6, 7, 2, 3, 6]])

In [203]:
arr

array([1, 2, 3, 4])

In [204]:
arr[0]

1

In [206]:
arr[1]

2

In [207]:
arr1

array([[2, 7, 2, 7, 5, 2],
       [1, 7, 1, 9, 9, 4],
       [2, 2, 1, 2, 7, 6],
       [8, 4, 8, 1, 1, 1],
       [4, 6, 7, 2, 3, 6]])

In [208]:
arr1[0]

array([2, 7, 2, 7, 5, 2])

In [209]:
arr1[0][1]

7

In [210]:
arr1[0][0]

2

In [213]:
arr1[0][1:4] # to get range [:] use this last excluded ex 4 is excluded in this

array([7, 2, 7])

In [215]:
arr1[0, [1, 2, 4]] # to get only selected values from columns, rows

array([7, 2, 5])

In [217]:
arr1[2:4, [2, 3]]

array([[1, 2],
       [8, 1]])

In [218]:
arr1[2:4]

array([[2, 2, 1, 2, 7, 6],
       [8, 4, 8, 1, 1, 1]])

In [219]:
arr1[2:4, [0, 2]]

array([[2, 1],
       [8, 8]])

In [220]:
arr1[2:4, [0:2]]

SyntaxError: invalid syntax (1159162006.py, line 1)

In [222]:
arr1[2:5, 0:2] # slicing

array([[2, 2],
       [8, 4],
       [4, 6]])

In [228]:
arr1[[2,4]]

array([[2, 2, 1, 2, 7, 6],
       [4, 6, 7, 2, 3, 6]])

In [229]:
arr1[[2,4], [0,2]]

array([2, 7])

In [230]:
arr1

array([[2, 7, 2, 7, 5, 2],
       [1, 7, 1, 9, 9, 4],
       [2, 2, 1, 2, 7, 6],
       [8, 4, 8, 1, 1, 1],
       [4, 6, 7, 2, 3, 6]])

In [231]:
arr1[2]

array([2, 2, 1, 2, 7, 6])

In [232]:
arr1[2, 4]

7

In [234]:
arr1[[2,4]] # selecting specific column

array([[2, 2, 1, 2, 7, 6],
       [4, 6, 7, 2, 3, 6]])

In [236]:
arr1[2:5] # slicing

array([[2, 2, 1, 2, 7, 6],
       [8, 4, 8, 1, 1, 1],
       [4, 6, 7, 2, 3, 6]])

In [237]:
arr1[[2,4],[1,3]]

array([2, 2])

In [242]:
arr1[2:4, [1,3]]

array([[2, 2],
       [4, 1]])

In [244]:
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))

In [245]:
arr1

array([[2, 1, 2],
       [2, 2, 2],
       [1, 1, 2]])

In [246]:
arr2

array([[2, 1, 1],
       [1, 1, 1],
       [1, 2, 1]])

In [247]:
arr1 + arr2 # it is index wise addition

array([[4, 2, 3],
       [3, 3, 3],
       [2, 3, 3]])

In [248]:
arr1 - arr2 # it is index wise subtraction

array([[ 0,  0,  1],
       [ 1,  1,  1],
       [ 0, -1,  1]])

In [249]:
arr1 * arr2 # it is index wise multiplication

array([[4, 1, 2],
       [2, 2, 2],
       [1, 2, 2]])

In [250]:
# Matrix Multiplication / Dot Product

arr1

array([[2, 1, 2],
       [2, 2, 2],
       [1, 1, 2]])

In [251]:
arr2

array([[2, 1, 1],
       [1, 1, 1],
       [1, 2, 1]])

In [252]:
arr1 @ arr2

array([[7, 7, 5],
       [8, 8, 6],
       [5, 6, 4]])

In [253]:
arr1 / arr2

array([[1. , 1. , 2. ],
       [2. , 2. , 2. ],
       [1. , 0.5, 2. ]])

In [254]:
arr1 / 0

C:\Users\pulki\AppData\Local\Temp\ipykernel_14328\824215542.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [255]:
# Broad Casting

In [257]:
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [261]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [262]:
a = np.array([1, 2, 3, 4])

In [263]:
a

array([1, 2, 3, 4])

In [264]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [265]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a = np.array([1, 2, 3]) # cannot transpose this because to transposenyou need 2d array

In [278]:
a = np.array([[1, 2, 3]])

In [279]:
a

array([[1, 2, 3]])

In [280]:
a.T

array([[1],
       [2],
       [3]])

In [282]:
arr + a.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [283]:
arr1

array([[2, 1, 2],
       [2, 2, 2],
       [1, 1, 2]])

In [285]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.41421356, 1.41421356],
       [1.        , 1.        , 1.41421356]])

In [286]:
np.log10(arr1)

array([[0.30103, 0.     , 0.30103],
       [0.30103, 0.30103, 0.30103],
       [0.     , 0.     , 0.30103]])

In [287]:
np.exp(arr1)

array([[7.3890561 , 2.71828183, 7.3890561 ],
       [7.3890561 , 7.3890561 , 7.3890561 ],
       [2.71828183, 2.71828183, 7.3890561 ]])

In [288]:
a

array([[1, 2, 3]])

In [289]:
np.min(a)

1

In [290]:
arr1

array([[2, 1, 2],
       [2, 2, 2],
       [1, 1, 2]])

In [291]:
np.min(arr1)

1

In [292]:
np.max(arr1)

2

In [293]:
arr1

array([[2, 1, 2],
       [2, 2, 2],
       [1, 1, 2]])

In [294]:
arr1.T

array([[2, 2, 1],
       [1, 2, 1],
       [2, 2, 2]])

In [295]:
arr1.flatten() # reduce higher dimension to 1d

array([2, 1, 2, 2, 2, 2, 1, 1, 2])

In [296]:
# expand_dims >> expands the array by inserting a new axis

In [300]:
arr = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3]])

In [301]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [302]:
np.sum(arr)

27

In [303]:
np.sum(arr, axis = 0) # axis 0 = row wise

array([ 6,  9, 12])

In [304]:
np.sum(arr, axis = 1) # axis 1 = column wise

array([ 6, 15,  6])

In [305]:
# expand_dims >> expands the dimension of array

arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [306]:
arr.ndim

1

In [314]:
arr1 = np.expand_dims(arr, axis = 0)
arr1

array([[1, 2, 3, 4]])

In [310]:
arr1.ndim

2

In [313]:
arr2 = np.expand_dims(arr, axis = 1)
arr2

array([[1],
       [2],
       [3],
       [4]])

In [317]:
arr2.ndim

2

In [318]:
arr3 = np.expand_dims(arr1, axis = 0)
arr3

array([[[1, 2, 3, 4]]])

In [320]:
arr4 = np.expand_dims(arr1, axis = 1)
arr4

array([[[1, 2, 3, 4]]])

In [321]:
arr4.shape

(1, 1, 4)

In [322]:
arr

array([1, 2, 3, 4])

In [323]:
arr = np.zeros((3, 4))

In [324]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [325]:
arr1  = np.expand_dims(arr, axis = 0)
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [326]:
arr1  = np.expand_dims(arr, axis = 1)
arr1

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])