In [4]:
import numpy as np
data = np.array([[1],[2],[3]])

In [5]:
data.ndim

2

In [6]:
data

array([[1],
       [2],
       [3]])

In [10]:
a = np.squeeze(data)

In [11]:
a

array([1, 2, 3])

In [9]:
a.ndim

1

In [15]:
# repeat
data

array([[1],
       [2],
       [3]])

In [17]:
np.repeat(data, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [18]:
a = np.array([[1, 2], [3, 4]])

In [19]:
a

array([[1, 2],
       [3, 4]])

In [22]:
b = np.repeat(a, 2)

In [23]:
b

array([1, 1, 2, 2, 3, 3, 4, 4])

In [25]:
np.expand_dims(b, axis = 1)

array([[1],
       [1],
       [2],
       [2],
       [3],
       [3],
       [4],
       [4]])

In [20]:
np.repeat(a, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [26]:
np.repeat(a, 2, axis = 1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [27]:
np.repeat(a, 2, axis = 0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [29]:
data

array([[1],
       [2],
       [3]])

In [30]:
np.roll(data, 1)

array([[3],
       [1],
       [2]])

In [32]:
np.roll(data, -2)

array([[3],
       [1],
       [2]])

In [33]:
np.roll(data, -1)

array([[2],
       [3],
       [1]])

In [31]:
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [34]:
a = np.array([[[1, 2], [3, 4], [5, 6]]])

In [39]:
a

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [40]:
np.roll(a, 1)

array([[[6, 1],
        [2, 3],
        [4, 5]]])

In [41]:
np.roll(a, 2, axis = 0)

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [42]:
# binary operation on array

In [43]:
arr1 = np.random.randint(1, 10, (3, 4))
arr2 = np.random.randint(1, 10, (3, 4))

In [44]:
arr1

array([[2, 3, 7, 9],
       [3, 2, 1, 4],
       [3, 7, 7, 3]])

In [45]:
arr2

array([[1, 6, 6, 8],
       [9, 5, 8, 8],
       [7, 2, 6, 6]])

In [46]:
arr1 + arr2

array([[ 3,  9, 13, 17],
       [12,  7,  9, 12],
       [10,  9, 13,  9]])

In [47]:
arr1 - arr2

array([[ 1, -3,  1,  1],
       [-6, -3, -7, -4],
       [-4,  5,  1, -3]])

In [48]:
arr1 * arr2

array([[ 2, 18, 42, 72],
       [27, 10,  8, 32],
       [21, 14, 42, 18]])

In [49]:
arr1 / arr2

array([[2.        , 0.5       , 1.16666667, 1.125     ],
       [0.33333333, 0.4       , 0.125     , 0.5       ],
       [0.42857143, 3.5       , 1.16666667, 0.5       ]])

In [50]:
arr1 ** arr2

array([[       2,      729,   117649, 43046721],
       [   19683,       32,        1,    65536],
       [    2187,       49,   117649,      729]])

In [51]:
arr1 > arr2

array([[ True, False,  True,  True],
       [False, False, False, False],
       [False,  True,  True, False]])

In [53]:
arr1

array([[2, 3, 7, 9],
       [3, 2, 1, 4],
       [3, 7, 7, 3]])

In [54]:
~arr1

array([[ -3,  -4,  -8, -10],
       [ -4,  -3,  -2,  -5],
       [ -4,  -8,  -8,  -4]])

In [56]:
# numpy string function

In [57]:
arr = np.array(['pw', 'skills'])

In [58]:
arr

array(['pw', 'skills'], dtype='<U6')

In [59]:
np.char.upper(arr)

array(['PW', 'SKILLS'], dtype='<U6')

In [60]:
np.char.upper(np.array(['Ajay']))

array(['AJAY'], dtype='<U4')

In [61]:
np.char.capitalize(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [62]:
np.char.title(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [63]:
# Mathematical Function

In [64]:
arr1

array([[2, 3, 7, 9],
       [3, 2, 1, 4],
       [3, 7, 7, 3]])

In [65]:
np.sin(arr1)

array([[ 0.90929743,  0.14112001,  0.6569866 ,  0.41211849],
       [ 0.14112001,  0.90929743,  0.84147098, -0.7568025 ],
       [ 0.14112001,  0.6569866 ,  0.6569866 ,  0.14112001]])

In [66]:
np.tan(arr1)

array([[-2.18503986, -0.14254654,  0.87144798, -0.45231566],
       [-0.14254654, -2.18503986,  1.55740772,  1.15782128],
       [-0.14254654,  0.87144798,  0.87144798, -0.14254654]])

In [67]:
np.log10(arr1)

array([[0.30103   , 0.47712125, 0.84509804, 0.95424251],
       [0.47712125, 0.30103   , 0.        , 0.60205999],
       [0.47712125, 0.84509804, 0.84509804, 0.47712125]])

In [68]:
np.exp(arr1)

array([[7.38905610e+00, 2.00855369e+01, 1.09663316e+03, 8.10308393e+03],
       [2.00855369e+01, 7.38905610e+00, 2.71828183e+00, 5.45981500e+01],
       [2.00855369e+01, 1.09663316e+03, 1.09663316e+03, 2.00855369e+01]])

In [69]:
np.power(arr1, 3)

array([[  8,  27, 343, 729],
       [ 27,   8,   1,  64],
       [ 27, 343, 343,  27]], dtype=int32)

In [70]:
np.mean(arr1)

4.25

In [71]:
np.max(arr1)

9

In [72]:
np.var(arr1)

6.020833333333333

In [73]:
np.std(arr1)

2.4537386440559095

In [74]:
arr1 - arr2

array([[ 1, -3,  1,  1],
       [-6, -3, -7, -4],
       [-4,  5,  1, -3]])

In [75]:
np.subtract(arr1, arr2)

array([[ 1, -3,  1,  1],
       [-6, -3, -7, -4],
       [-4,  5,  1, -3]])

In [76]:
arr1 * arr2

array([[ 2, 18, 42, 72],
       [27, 10,  8, 32],
       [21, 14, 42, 18]])

In [77]:
np.multiply(arr1, arr2)

array([[ 2, 18, 42, 72],
       [27, 10,  8, 32],
       [21, 14, 42, 18]])

In [78]:
np.mod(arr1, arr2) # return element wise remainder

array([[0, 3, 1, 1],
       [3, 2, 1, 4],
       [3, 1, 1, 3]])

In [79]:
np.power(arr1, arr2)

array([[       2,      729,   117649, 43046721],
       [   19683,       32,        1,    65536],
       [    2187,       49,   117649,      729]])

In [80]:
np.sqrt(arr1)

array([[1.41421356, 1.73205081, 2.64575131, 3.        ],
       [1.73205081, 1.41421356, 1.        , 2.        ],
       [1.73205081, 2.64575131, 2.64575131, 1.73205081]])

In [81]:
# sort search

In [82]:
arr = np.array([5, 6, 1, 2])

In [83]:
arr

array([5, 6, 1, 2])

In [84]:
np.sort(arr)

array([1, 2, 5, 6])

In [85]:
np.searchsorted(arr, 3)

4

In [89]:
arr1 = np.array([0, 1, 2, 3, 0, 4])
np.count_nonzero(arr1)

4

In [90]:
arr1 > 0

array([False,  True,  True,  True, False,  True])

In [91]:
np.where(arr > 0)

(array([0, 1, 2, 3], dtype=int64),)

In [92]:
np.extract(arr1 > 0, arr1)

array([1, 2, 3, 4])

In [93]:
arr1.byteswap()

array([       0, 16777216, 33554432, 50331648,        0, 67108864])

In [94]:
#matrix >> 2d array

In [95]:
import numpy.matlib as nm

In [96]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [97]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [98]:
# Numpy Linear Algebra

In [99]:
arr1 = np.random.randint(1, 10, (3, 4))
arr2 = np.random.randint(1, 10, (3, 4))

In [103]:
arr1 = np.array([[2, 3], [4, 5]])
arr2 = np.array([[1, 3], [4, 5]])

In [104]:
arr2

array([[1, 3],
       [4, 5]])

In [105]:
arr1 @ arr2

array([[14, 21],
       [24, 37]])

In [106]:
a = np.array([[7, 5, -3], [3, -5, 2], [5, 3, -7]])

In [107]:
a

array([[ 7,  5, -3],
       [ 3, -5,  2],
       [ 5,  3, -7]])

In [108]:
b = np.array([16, -8, 0])

In [109]:
b

array([16, -8,  0])

In [110]:
np.linalg.solve(a, b)

array([1., 3., 2.])

In [111]:
5*2 -3*4

-2

In [114]:
arr1

array([[2, 3],
       [4, 5]])

In [112]:
np.linalg.det(arr1)

-2.0

In [113]:
np.linalg.inv(arr1)

array([[-2.5,  1.5],
       [ 2. , -1. ]])